import Anthropic from "@anthropic-ai/sdk";
import { Resend } from "resend";
import PDFDocument from "pdfkit";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const resend = new Resend(process.env.RESEND_API_KEY);

export const config = { maxDuration: 300 };

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const brand = req.body;
  if (!brand?.brand_name) return res.status(400).json({ error: "Missing brand data" });

  console.log("=== NEW SUBMISSION ===");
  console.log("Submitter:", brand.submitter_name, "|", brand.submitter_email);
  console.log("Brand:", brand.brand_name, "|", brand.website);
  console.log("Full data:", JSON.stringify(brand));
  console.log("=== END SUBMISSION ===");

  try {
    const conceptsRaw = await callClaude(
      "You are an expert social media strategist. Respond ONLY with a valid JSON array. No markdown fences, no preamble.",
      buildConceptsPrompt(brand)
    );
    const concepts = JSON.parse(conceptsRaw.replace(/```json|```/g, "").trim());
    const withScripts = await generateAllScripts(brand, concepts);

    try {
      const pdfBuffer = await buildPdf(brand, withScripts);
      const safeName = (brand.brand_name || "brand").replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "");
      const result = await resend.emails.send({
        from: "Schreier AI <todd@schreier.ai>",
        to: [process.env.ADMIN_EMAIL || "todd@schreier.ai"],
        subject: `[Schreier.AI] 30 Concepts — ${brand.brand_name} (${brand.submitter_name})`,
        text: buildEmailSummary(brand),
        attachments: [
          {
            filename: `${safeName}-content-concepts.pdf`,
            content: pdfBuffer.toString("base64"),
          },
        ],
      });
      console.log("Resend result:", JSON.stringify(result));
      if (result.error) {
        console.error("Resend error detail:", JSON.stringify(result.error));
      }
    } catch (emailErr) {
      console.error("EMAIL FAILED:", emailErr.message);
    }

    return res.status(200).json({ success: true });

  } catch (err) {
    console.error("Generate error:", err.message);
    return res.status(500).json({ error: err.message || "Generation failed" });
  }
}

function buildEmailSummary(brand) {
  let msg = `New Schreier.AI submission — the branded PDF with all 30 concepts and scripts is attached, ready to forward.\n\n`;
  msg += `SUBMITTER: ${brand.submitter_name} | ${brand.submitter_email}\n`;
  msg += `BRAND: ${brand.brand_name} | ${brand.website}\n`;
  msg += `NICHE: ${brand.niche}\n`;
  msg += `PLATFORMS: ${brand.platforms}\n`;
  msg += `GOAL: ${brand.content_goal}\n`;
  msg += `FOLLOWERS: ${brand.followers}\n`;
  msg += `COMPETITORS: ${brand.competitors}\n`;
  msg += `IDEAL CUSTOMER: ${brand.ideal_customer}\n`;
  msg += `PROBLEMS: ${brand.customer_problems}\n`;
  return msg;
}

// Brand tokens for the PDF — matches schreiergroup.com
const INK = "#0e0e0e";
const CYAN = "#10b9e6";
const CREAM = "#f5f3ef";
const GRAY = "#555555";

function buildPdf(brand, concepts) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER", bufferPages: true, margins: { top: 64, bottom: 64, left: 60, right: 60 } });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const W = doc.page.width;

    // ---- COVER ----
    doc.rect(0, 0, W, doc.page.height).fill(CREAM);
    doc.rect(0, 0, W, 120).fill(INK);
    doc.rect(0, 120, W, 4).fill(CYAN);
    doc.font("Helvetica-Bold").fontSize(20).fillColor("#ffffff").text("SCHREIER GROUP", 60, 48, { characterSpacing: 3 });
    doc.font("Helvetica").fontSize(8).fillColor("#bdbdbd").text("A FAMILY FIRM HELPING SMALL BUSINESS OWNERS GROW", 60, 76, { characterSpacing: 1.5 });

    doc.font("Helvetica-Bold").fontSize(44).fillColor(INK).text("30 CONTENT\nCONCEPTS", 60, 230, { lineGap: 4 });
    doc.font("Helvetica").fontSize(13).fillColor(GRAY).text("with full teleprompter-ready scripts", 60, 348);

    doc.rect(60, 400, 60, 3).fill(CYAN);
    doc.font("Helvetica-Bold").fontSize(16).fillColor(INK).text(`Prepared for ${brand.brand_name}`, 60, 424);
    doc.font("Helvetica").fontSize(10.5).fillColor(GRAY)
      .text(`${brand.submitter_name}  ·  ${brand.website}`, 60, 448)
      .text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), 60, 464)
      .text(`Platforms: ${brand.platforms}`, 60, 480);

    doc.font("Helvetica").fontSize(8.5).fillColor(GRAY)
      .text("Generated by Schreier.AI — the in-house AI of Schreier Group LLC  ·  schreiergroup.com", 60, doc.page.height - 80);

    // ---- CONCEPTS ----
    doc.addPage();
    concepts.forEach((c, i) => {
      if (i > 0 && doc.y > doc.page.height - 220) doc.addPage();

      const startY = doc.y;
      doc.font("Helvetica-Bold").fontSize(11).fillColor(CYAN)
        .text(`CONCEPT ${String(c.number).padStart(2, "0")}`, 60, startY, { characterSpacing: 1, continued: false });
      doc.font("Helvetica").fontSize(8).fillColor(GRAY)
        .text(`${(c.type || "").toUpperCase()}   ·   ${(c.platform || "").toUpperCase()}`, 60, startY + 2, { align: "right", width: W - 120 });
      doc.moveDown(0.6);

      doc.font("Helvetica-Bold").fontSize(14).fillColor(INK).text(c.hook || "", { lineGap: 2 });
      doc.moveDown(0.35);
      doc.font("Helvetica").fontSize(10).fillColor("#333333").text(c.concept || "", { lineGap: 2.5 });
      doc.moveDown(0.5);

      doc.font("Helvetica-Bold").fontSize(8).fillColor(GRAY).text("SCRIPT", { characterSpacing: 1.5 });
      doc.moveDown(0.25);
      doc.font("Helvetica").fontSize(9.5).fillColor(INK).text((c.script || "").trim(), { lineGap: 2.2 });
      doc.moveDown(0.8);

      if (i < concepts.length - 1) {
        doc.moveTo(60, doc.y).lineTo(W - 60, doc.y).lineWidth(0.5).strokeColor("#ddd6c9").stroke();
        doc.moveDown(0.8);
      }
    });

    // Footers on every page except the cover (drawn last — buffered pages,
    // bottom margin zeroed so footer text can never trigger a new page)
    const range = doc.bufferedPageRange();
    for (let i = 1; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      const savedBottom = doc.page.margins.bottom;
      doc.page.margins.bottom = 0;
      const y = doc.page.height - 40;
      doc.fontSize(7.5).fillColor(GRAY).font("Helvetica")
        .text(`SCHREIER GROUP  ·  schreiergroup.com  ·  Concepts for ${brand.brand_name}`, 60, y, { lineBreak: false })
        .text(String(i), W - 90, y, { width: 30, align: "right", lineBreak: false });
      doc.page.margins.bottom = savedBottom;
    }

    doc.end();
  });
}

async function callClaude(system, user) {
  const msg = await anthropic.messages.create({
    model: "claude-sonnet-5",
    max_tokens: 4000,
    system,
    messages: [{ role: "user", content: user }],
  });
  return msg.content.filter(b => b.type === "text").map(b => b.text).join("");
}

function buildConceptsPrompt(d) {
  return `Generate exactly 30 social media video concepts for the brand below.

Return ONLY a JSON array of 30 objects with these fields:
- "number": integer 1-30
- "hook": opening line / video title (punchy, scroll-stopping, under 15 words)
- "concept": 2-3 sentence description of the video structure and key message
- "platform": one of the brand's target platforms
- "type": e.g. Tutorial, Hot take, Story, POV, Myth-busting, Behind the scenes, etc.

BRAND BRIEF:
Brand: ${d.brand_name} (${d.website})
Niche: ${d.niche}
What makes them different: ${d.differentiator}
Ideal customer: ${d.ideal_customer}
Top customer problems: ${d.customer_problems}
Customer voice: ${d.customer_voice || "Not provided"}
Competitors: ${d.competitors}
Competitor strengths: ${d.competitor_good || "Not provided"}
Content gaps: ${d.content_gaps || "Not provided"}
Brand personality: ${d.brand_personality || "Not provided"}
Content goal: ${d.content_goal}
Target platforms: ${d.platforms}
Topics to AVOID: ${d.avoid || "None"}
Upcoming events: ${d.upcoming || "None"}
Posting frequency: ${d.posting_freq}
Follower count: ${d.followers}

Rules:
- Spread concepts across ALL listed platforms proportionally
- Vary content types widely
- Every hook must be specific to this brand
- Make each concept immediately actionable`;
}

async function generateAllScripts(brand, concepts) {
  const batchSize = 5;
  const result = [...concepts];
  for (let i = 0; i < concepts.length; i += batchSize) {
    const batch = concepts.slice(i, i + batchSize);
    const scripts = await Promise.all(batch.map((c) => generateScript(brand, c)));
    scripts.forEach((script, j) => { result[i + j] = { ...result[i + j], script }; });
    if (i + batchSize < concepts.length) await sleep(500);
  }
  return result;
}

async function generateScript(brand, concept) {
  return callClaude(
    "You are a professional video scriptwriter. Write exactly as requested — no preamble, just the script.",
    `Write a complete teleprompter script for this social media video.

BRAND: ${brand.brand_name}
PLATFORM: ${concept.platform}
VIDEO TYPE: ${concept.type}
HOOK: ${concept.hook}
CONCEPT: ${concept.concept}
BRAND PERSONALITY: ${brand.brand_personality || "Professional and approachable"}
IDEAL CUSTOMER: ${brand.ideal_customer}
TOPICS TO AVOID: ${brand.avoid || "None"}

Requirements:
- Start with the hook line word-for-word
- Natural, conversational, platform-appropriate tone
- Include [PAUSE], [SMILE], [CUT TO:], [B-ROLL: description] stage directions
- End with a clear call to action
- Write ONLY the script`
  );
}

function sleep(ms) { return new Promise((r) => setTimeout(r, ms)); }
